//
//  Data.swift
//  Restaurant
//
//  Created by Andrew Hinson on 10/26/17.
//  Copyright © 2017 Andrew Hinson. All rights reserved.
//

import Foundation

class Data{
    static var sampleData = [
        RestaurantModel(restuarantName: "Wendys", restuarantType: "Fast Food", restuarantImage: "wendys", restuarantBodyText:"Wendy's is an American international fast food restaurant chain founded by Dave Thomas on November 15, 1969, in Columbus, Ohio. The company moved its headquarters to Dublin, Ohio, on January 29, 2006."),
        RestaurantModel(restuarantName: "Burger King", restuarantType: "Fast Food", restuarantImage: "burgerking", restuarantBodyText:"Every day, more than 11 million guests visit BURGER KING® restaurants around the world. And they do so because our restaurants are known for serving high-quality, great-tasting, and affordable food. Founded in 1954, BURGER KING® is the second largest fast food hamburger chain in the world. The original HOME OF THE WHOPPER®, our commitment to premium ingredients, signature recipes, and family-friendly dining experiences is what has defined our brand for more than 50 successful years."),
        RestaurantModel(restuarantName: "McDonalds", restuarantType: "Fast Food", restuarantImage: "mcDonalds", restuarantBodyText:"In 1917, 15-year-old Ray Kroc lied about his age to join the Red Cross as an ambulance driver, but the war ended before he completed his training. He then worked as a piano player, a paper cup salesman and a Multimixer salesman. In 1954, he visited a restaurant in San Bernardino, California that had purchased several Multimixers. There he found a small but successful restaurant run by brothers Dick and Mac McDonald, and was stunned by the effectiveness of their operation. They produced a limited menu, concentrating on just a few items – burgers, fries and beverages – which allowed them to focus on quality and quick service. They were looking for a new agent and Kroc saw an opportunity. In 1955, he founded McDonald’s System, Inc., a predecessor of the McDonald’s Corporation, and six years later bought the exclusive rights to the McDonald’s name. By 1958, McDonald’s had sold its 100 millionth hamburger."),
        RestaurantModel(restuarantName: "Olive Garden", restuarantType: "Italian", restuarantImage: "oliveGarden", restuarantBodyText:"Today, the Olive Garden family of 800+ restaurants is evolving the brand with our customers' favorites in mind. With reinvigorated dishes, a refreshed website, a restructured logo, and remodeling of select restaurants, we aim to make every guest experience feel more like modern Italy."),
        RestaurantModel(restuarantName: "Five Guys", restuarantType: "Burger Joint", restuarantImage: "fiveGuys", restuarantBodyText:"Five Guys has been a Washington, DC area favorite since 1986 when Jerry and Janie Murrell offered sage advice to the four young Murrell brothers:Start a business or go to college. The business route won and the Murrell family opened a carry-out burger joint in Arlington, Virginia."),
        RestaurantModel(restuarantName: "Red Robin", restuarantType: "Burger Joint", restuarantImage: "redRobin", restuarantBodyText:"Red Robin, is an American chain of casual dining restaurants founded in September 1969 in Seattle, Washington. In 1979, the first franchised Red Robin restaurant was opened in Yakima, Washington."),
        RestaurantModel(restuarantName: "Steak N Shake", restuarantType: "Fast Food", restuarantImage: "steakNShake", restuarantBodyText:"Gus Belt (born in Morrisonville, Illinois) founded Steak 'n Shake in Normal, Illinois in February 1934, after serving four years in the United States Marine Corps. He converted the combination gas station and chicken restaurant that he owned (Shell's Chicken) into a hamburger stand."),
        RestaurantModel(restuarantName: "Chick-Fil-A", restuarantType: "Spiritual Chicken", restuarantImage: "chickFilA", restuarantBodyText:"Cathy opened the first true Chick-fil-A at age 46, in suburban Atlanta. In 1967, two years after finally perfecting his chicken recipe, Cathy was ready to open a restaurant based purely on the sandwich. The first location was in Atlanta's Greenbriar Mall and was only 384 square feet."),
        RestaurantModel(restuarantName: "Outback Steakhouse", restuarantType: "Aussie Cousine", restuarantImage: "outBack", restuarantBodyText:"It was founded in February 1988 in Tampa by Bob Basham, Chris T. Sullivan, Trudy Cooper, and Tim Gannon, and it was owned and operated in the United States by OSI Restaurant Partners until it was acquired by Bloomin' Brands, and by other franchise and venture agreements internationally."),
        RestaurantModel(restuarantName: "Papa Johns", restuarantType: "Pizza", restuarantImage: "papaJohns", restuarantBodyText:"The Papa John's restaurant was founded in 1984 when Papa John Schnatter knocked out a broom closet in the back of his father's tavern, Mick's Lounge, in Jeffersonville, Indiana.He then sold his 1971 Camaro Z28 to purchase US$1,600 worth of used pizza equipment and began selling pizzas to the tavern's customers out of the converted closet.His pizzas proved so popular that one year later he was able to move into an adjoining space. Dipping sauce specifically for pizza was invented by Papa John's Pizza that same year, and has since become popular when eating pizza, especially the crust.In 2009, Schnatter got the Camaro back after offering a reward of $250,000 for the car."),
        RestaurantModel(restuarantName: "KC Finns", restuarantType: "Burger Joint", restuarantImage: "kcFinns", restuarantBodyText:"Spicy jalapeno bacon ipsum dolor amet pork chop sausage porchetta alcatra tenderloin capicola tri-tip doner brisket turducken. Kevin boudin frankfurter pork chop meatloaf pastrami short ribs. Tenderloin pancetta brisket, bresaola t-bone turducken boudin fatback chicken tri-tip andouille hamburger swine kevin beef ribs. Strip steak jowl leberkas rump, andouille pork belly corned beef flank short ribs kevin bacon short loin. "),
        RestaurantModel(restuarantName: "Taco Bell", restuarantType: "Fast Food", restuarantImage: "tacoBell", restuarantBodyText:"Taco Bell was founded by Glen Bell, who first opened a hot dog stand called Bell's Drive-In in San Bernardino, California in 1946 when he was 23 years old. In 1950, he opened Bell's Hamburgers and Hot Dogs in San Bernardino's West Side barrio. According to Gustavo Arellano, author of Taco USA: How Mexican Food Conquered America, Bell watched long lines of customers at a Mexican restaurant called the Mitla Cafe, located across the street, which attracted a dedicated customer base for its hard-shelled tacos.Bell began eating there regularly, attempting to reverse-engineer the recipe, and eventually won the confidence of the proprietors such that they allowed him to see how the tacos and other foods were prepared.In late 1951 or early 1952, he took what he had learned and opened a new stand, this time selling tacos under the name of Taco-Tia.Over the next few years, Bell owned and operated a number of restaurants in southern California including four called El Taco. Bell sold the El Tacos to his partner and built the first Taco Bell in Downey in 1962. In 1962, he sold Taco-Tia. Kermit Becky, a former Los Angeles police officer, bought the first Taco Bell franchise from Glen Bell in 1964, and located it in Torrance. The company grew rapidly, and by 1967, the 100th restaurant opened at 400 South Brookhurst in Anaheim. In 1968, its first franchise location east of the Mississippi River opened in Springfield, Ohio.In 1970, Taco Bell went public with 325 restaurants.")
    
    
    ]
}
